name: Lint and Test

on:
  workflow_call:
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input selected App to STDOUT
        run: echo  The selected App is ${{ inputs.selectApp }} 

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Node modules
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Unit & Integration tests
        run: yarn test

      - name: Install detox-cli
        run: npm install -g detox-cli

      - name: Install applesimutils & detox-cli
        run: brew install applesimutils

      - name: e2e tests
        run: yarn detox:build:ios && detox:test:ios

      - name: Collect all coverage
        run: yarn coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Unit & Integration tests
      #   run: yarn test
      # - name: Unit & Integration tests
      #   run: yarn test

      # - name: Jest coverage report
      #   uses: ArtiomTr/jest-coverage-report-action@v2.0.6
      #   with:
      #     coverage-file: ./jest-report.json
      #     base-coverage-file: ./jest-report.json