name: Pull Request into Master, Develop and Preprod
on: [push]
jobs:
  #First job
  # install-and-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Use Node.js 18
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: "yarn"

  #     - name: Install Node modules
  #       run: yarn install

  #     - name: Linting
  #       run: yarn lint

      # - name: Unit & Integration tests
      #   run: yarn test

      # - name: Jest coverage report
      #   uses: ArtiomTr/jest-coverage-report-action@v2.0.6
      #   with:
      #     coverage-file: ./jest-report.json
      #     base-coverage-file: ./jest-report.json

  versioning:
    uses: ./.github/workflows/release.yml
    with:
      tag-suffix: dev
      release-title: Dev Build
    secrets: inherit

  #Second Job
  build-android:
    needs: versioning
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  # Third Job
  # build-ios:
  #   needs: install-and-test
  #   uses: ./.github/workflows/build-ios.yml
  #   secrets: inherit