name: Pull Request into Master, Develop and Preprod
on: [push]
jobs:
  #First job
  # install-and-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Use Node.js 18
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: "yarn"

  #     - name: Install Node modules
  #       run: yarn install

  #     - name: Linting
  #       run: yarn lint

      # - name: Unit & Integration tests
      #   run: yarn test

      # - name: Jest coverage report
      #   uses: ArtiomTr/jest-coverage-report-action@v2.0.6
      #   with:
      #     coverage-file: ./jest-report.json
      #     base-coverage-file: ./jest-report.json

  # Second Job
  # build-android:
  #   needs: install-and-test
  #   uses: build-android.yml
  #   secrets: inherit

  # Third Job
  # build-ios:
  #   needs: install-and-test
  #   uses: ./.github/workflows/build-ios.yml
  #   secrets: inherit

  # release-android:
  #   needs: install-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "18.x"
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: "2.x"
  #     - name: Install Fastlane
  #       run: cd packages/riderapp/android && bundle install && cd .. && cd .. && cd ..
  #     - name: Install packages
  #       run: yarn install
  #     - name: Execute Fastlane command
  #       run: cd packages/riderapp/android && fastlane test

  release-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"
          bundler-cache: true

      - name: Install Fastlane
        run: cd packages/riderapp/android && bundle install && cd .. && cd .. && cd ..

      - name: Install packages
        run: yarn install

      # - name: Run tests
      #   run:  cd packages/riderapp/android && bundle exec fastlane android test
    
      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}
    
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.jks"
          encodedString: ${{ secrets.KEYSTORE_FILE }}
    
      - name: Define version code with offset
        env:
            RUN_NUMBER: ${{ github.run_number }}
            INITIAL_VERSION_CODE: 1
        run: |
            VERSION_CODE=$((INITIAL_VERSION_CODE + RUN_NUMBER))
            echo "version_code=$VERSION_CODE" >> $GITHUB_ENV
    
      - name: Update version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: packages/riderapp/android/app/build.gradle
          versionCode: ${{ env.version_code }}
    
      - name: Build & deploy Android release
        run: cd packages/riderapp/android && bundle exec fastlane deploy
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            ${{ github.workspace }}/app/release
